### PR TITLE
Slight GUI polish on top of #168

### PR DESCRIPTION
**Pull request by smathot**
I changed the layout of the study panel such that the buttons sit on a row above the tabs, like this:

Screenshot from 2024-08-25 13-39-14

Otherwise it won't look nice except on very wide windows. Can you briefly check this and then merge? That also takes care of #168 then.

### CODE REVIEW

**Comment by kristian-lange** [comment]
I actually tried the grow/shrink layout and it worked on my laptop (Thinkpad with normal screen resolution). Even when I reduced the screen size a bit with the developer tools and opened the OMM's sidebar to squeeze it even more it was all fine with no wrapping. I'm not against a two rows solution but then we should take out the grow/shrink stuff because it's not necessary anymore and just confusing. It's up to you: two rows or grow/shrink?

**Comment by smathot** [comment]
We need two rows for this. The issue is not that it wraps on small windows, but that the tabs don't fit and show a kind of scroll button which you need to click in order to access the Statistics tab.

**Comment by kristian-lange** [comment]
Not sure what you mean. It looks fine in my browser. But if you prefer to rows, it will be two rows. I just have to remove the grow/shrink stuff.

[Screencast from 21.09.2024 10:05:47.webm](https://github.com/user-attachments/assets/ffd4768b-76b9-495e-9e76-5fa05e49eb0a)

**Comment by smathot** [comment]
This video looks good, indeed. What I experienced was that the tab bar shrunk so that the statistics option was no longer visible (but hidden behind a horizontal scroll button). We don't need to get to the bottom of why this behavior is different now. The way it is on your video is good, so go ahead and merge! (Can you do that because otherwise I may merge from the wrong point.)

**Pull request closed without merging**
