### PR TITLE
Add facilities for session data

### PR DESCRIPTION
**Pull request by dschreij**
@smathot there now are functions to maintain session data by using the `/sessions` endpoint. The relevant swagger documentation has been added and is hopefully self explanatory. Can you test this and see if it fits your requirements?

### CODE REVIEW

**Comment by smathot** [comment]
Before I test it: I see how this endpoint for data that is associated with a study and a participant. But how does it work for the data is shared across studies and/ or shared across participants. Do I indeed send a `null` id for the study and/ or particpant?

**Review by smathot — COMMENTED** [review]
I get the following error when trying to get session data through the Swagger docs.
Screenshot from 2021-09-09 13-12-20

**Comment by dschreij** [comment]
> Before I test it: I see how this endpoint for data that is associated with a study and a participant. But how does it work for the data is shared across studies and/ or shared across participants. Do I indeed send a null id for the study and/ or participant?

Since these are query parameters, you can just simply omit them, e.g.

```
GET/PUT /sessions?participant_id=abcsd&study_id=1
```
will get data for a study/ptcp combination

```
GET/PUT /sessions?study_id=1
```
will get data for this study (participant_id will be set to null implicitly)

```
GET/PUT /sessions
```
Set global data

**Comment by dschreij** [comment]
> I get the following error when trying to get session data through the Swagger docs.
Dit you create some data first? If you haven't set any data you will indeed get a 404 because there is no record for the parameters you passed.

**Comment by smathot** [comment]
It seems to work nicely for the most part, except two things that I ran into:

**Comment by dschreij** [comment]
What actions did you perform to get the error at 2.?

**Comment by smathot** [comment]
I go to Studies and then click on Attentional Capture. At that moment the following error message appears in the console (all at once):

```
ModelNotFoundException: E_MISSING_DATABASE_ROW: Cannot find database row for Study model
> More details: https://err.sh/adonisjs/errors/E_MISSING_DATABASE_ROW
    at Function.raise (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Exceptions/index.js:143:12)
    at Proxy.firstOrFail (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Lucid/QueryBuilder/index.js:434:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async StudyController.show (/home/sebastiaan/git/omm-server/app/Controllers/Http/StudyController.js:178:19)
    at async Server._routeHandler (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/framework/src/Server/index.js:121:25)
    at async JsonResponse.handle (/home/sebastiaan/git/omm-server/app/Middleware/JsonResponse.js:14:5)
    at async Auth.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async AuthInit.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async Shield.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async SessionMiddleware.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:242:7)
ModelNotFoundException: E_MISSING_DATABASE_ROW: Cannot find database row for Study model
> More details: https://err.sh/adonisjs/errors/E_MISSING_DATABASE_ROW
    at Function.raise (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Exceptions/index.js:143:12)
    at Proxy.firstOrFail (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Lucid/QueryBuilder/index.js:434:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async StudyController.fetchParticipants (/home/sebastiaan/git/omm-server/app/Controllers/Http/StudyController.js:1051:19)
    at async Server._routeHandler (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/framework/src/Server/index.js:121:25)
    at async JsonResponse.handle (/home/sebastiaan/git/omm-server/app/Middleware/JsonResponse.js:14:5)
    at async Auth.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async AuthInit.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async Shield.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async SessionMiddleware.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:242:7)
ModelNotFoundException: E_MISSING_DATABASE_ROW: Cannot find database row for Study model
> More details: https://err.sh/adonisjs/errors/E_MISSING_DATABASE_ROW
    at Function.raise (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Exceptions/index.js:143:12)
    at Proxy.firstOrFail (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Lucid/QueryBuilder/index.js:434:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async JobController.index (/home/sebastiaan/git/omm-server/app/Controllers/Http/JobController.js:74:19)
    at async Server._routeHandler (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/framework/src/Server/index.js:121:25)
    at async JsonResponse.handle (/home/sebastiaan/git/omm-server/app/Middleware/JsonResponse.js:14:5)
    at async Auth.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async AuthInit.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async Shield.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async SessionMiddleware.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:242:7)
ModelNotFoundException: E_MISSING_DATABASE_ROW: Cannot find database row for Study model
> More details: https://err.sh/adonisjs/errors/E_MISSING_DATABASE_ROW
    at Function.raise (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Exceptions/index.js:143:12)
    at Proxy.firstOrFail (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/lucid/src/Lucid/QueryBuilder/index.js:434:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async StudyController.participationStats (/home/sebastiaan/git/omm-server/app/Controllers/Http/StudyController.js:1177:19)
    at async Server._routeHandler (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/framework/src/Server/index.js:121:25)
    at async JsonResponse.handle (/home/sebastiaan/git/omm-server/app/Middleware/JsonResponse.js:14:5)
    at async Auth.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async AuthInit.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async Shield.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async SessionMiddleware.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:242:7)
TypeError: Cannot read property 'getParticipantQueuePositions' of null
    at StudyController.participantQueue (/home/sebastiaan/git/omm-server/app/Controllers/Http/StudyController.js:1265:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Server._routeHandler (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/framework/src/Server/index.js:121:25)
    at async JsonResponse.handle (/home/sebastiaan/git/omm-server/app/Middleware/JsonResponse.js:14:5)
    at async Auth.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/Auth.js:127:5)
    at async AuthInit.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:60:5)
    at async Shield.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/shield/src/Shield/index.js:417:5)
    at async SessionMiddleware.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/session/src/Session/Middleware.js:76:5)
    at async BodyParser.handle (/home/sebastiaan/git/omm-server/node_modules/@adonisjs/bodyparser/src/BodyParser/index.js:242:7) {
  status: 500
}
```

This also results in a red error in the GUI. However, otherwise the GUI appears to be fine. One oddity that may be related is that there is no experiment file uploaded for the attentional-capture experiment.

**Comment by dschreij** [comment]
Odd! I also always test with that study and haven't seen this, but will pay extra attention next time.

**Comment by dschreij** [comment]
I think I resolved 1). Session data is now deleted if a participant is revoked from a study.
I have reset my DB but don't see the errors described in 2) in my console when opening the attentional capture study. I cannot thus reproduce this. If there are any other pointers you can give me (e.g. used Node/npm versions, etc.) I can try again, but for me it just works without trouble.

**Comment by smathot** [comment]
Looks good! Can you tag this as a new release? Then I'll do the same for the client and @nclaidiere can start using it.

**Pull request merged**
